name: CI/CD Pipeline  

on:  
  push:  
    branches:  
      - main  # Ganti dengan nama branch yang Anda gunakan  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Set up PHP  
        uses: shivammathur/setup-php@v2  
        with:  
          php-version: '8.0'  # Ganti dengan versi PHP yang Anda gunakan  
          extensions: mbstring, xml, curl, etc.  
          ini-values: post_max_size=256M, upload_max_filesize=256M  

      - name: Install Composer dependencies  
        run: composer install --no-progress --no-suggest --prefer-dist  

      - name: Run Tests  
        run: vendor/bin/phpunit  # Hanya jika Anda memiliki unit test  